var Black_bishop = "qrc:/res/img/black_bishop.png"
var Black_king = "qrc:/res/img/black_king.png"
var Black_knight = "qrc:/res/img/black_knight.png"
var Black_pawn = "qrc:/res/img/black_pawn.png"
var Black_queen = "qrc:/res/img/black_queen.png"
var Black_rook = "qrc:/res/img/black_rook.png"
var None_piece = ""
var White_bishop = "qrc:/res/img/white_bishop.png"
var White_king = "qrc:/res/img/white_king.png"
var White_knight = "qrc:/res/img/white_knight.png"
var White_pawn = "qrc:/res/img/white_pawn.png"
var White_queen = "qrc:/res/img/white_queen.png"
var White_rook = "qrc:/res/img/white_rook.png"

var Back = "qrc:/res/img/back.png"
var Close = "qrc:/res/img/close.png"
